export const CONFIGS = {
  WEB_PUSH_EMAIL: process.env.WEB_PUSH_EMAIL,
  WEB_PUSH_PUBLIC_KEY: process.env.NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY,
  WEB_PUSH_PRIVATE_KEY: process.env.WEB_PUSH_PRIVATE_KEY,
};
